[package]
name = "salvation"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
rand = "0.8"
dashmap = "6.0"
crossbeam-utils = "0.8"
godot = { git = "https://github.com/godot-rust/gdext.git", features = [
    "api-4-4",
    "experimental-threads"
] }
